### PR TITLE
Secondary color in EditText fields

### PR DESCRIPTION
**Pull request by Viciouss**
#### Short description of what this resolves:
This resolves the EditText fields secondary color issue as much as possible.

#### Changes proposed in this pull request:

- added OnFocusChangeListener so that we can change the underline color on focus
- changed highlight color to grey to minimize the default colors that need to be fixed some other way
- switched cursor color to black for the same reason

**Fixes**: #15

### CODE REVIEW

**Comment by naushad-madakiya** [comment]
@Viciouss I can not see the changes reflected in the edit text for Idea dialog after building the app from your pull request. where red is selected as a secondary color.

Seems the issue is with `OnFocusChangeListener` It's not executed when I open dialog or change focus on `EditText`

screenshot_2017-10-10-12-05-03-505_appbox gameideas

**Comment by Viciouss** [comment]
I can reproduce this issue. After creating an idea and then restarting the app, the same happened to me. I will have a look at it tomorrow.

**Comment by naushad-madakiya** [comment]
@Viciouss sure, thanks

**Comment by Viciouss** [comment]
Interestingly enough the framework seems to reuse the EditText objects as I did not change both, the create and the edit one. At least that's the only way I can explain that both windows showed the secondary colors while I was testing. I fixed this and I also fixed the focus issue which made both the idea and the comment colored with the secondary color at the same time. I tried it several times now, including killing and restarting the app and it works just fine.

**Comment by naushad-madakiya** [comment]
Thanks, I will review and merge soon meanwhile you can you work on the conflicts?

**Comment by Viciouss** [comment]
Done.

**Comment by naushad-madakiya** [comment]
`EditText` color changes working as expected. I have tried a scenario I think there is an issue with this,
- For the new installation, it works as expected.
- If app is already installed with the previous version and we upgrade with these changes, It doesn't affect the `EditText`. 

Can you try to reproduce this?

**Comment by Viciouss** [comment]
I installed the version before I made my changes, switched the secondary color and then updated it to the version that contains my code changes. Opening the window with the EditText, I instantly got all my changes for the secondary color without any issue.

**Pull request merged**
